# DNS防泄露版本
# 不是必须请勿用，不懂不要随便更改DNS模块
# 必读！！！
# 注意规则在满足自己需求情况下，尽量做到精简，不要过度复杂，以免影响性能。
# 跑裸核用户请自行去掉下方控制面板模块的注释。
# 机场订阅
proxy-providers:
  Airport1:
    url: "机场订阅填到这里，两端引号不要去掉，不要填写到下方链接里去！！"
    type: http
    interval: 86400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
    proxy: 直连

# 节点信息
proxies:
  - {name: 直连, type: direct}

# 全局配置 
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7894
allow-lan: true
bind-address: "*"
ipv6: false
unified-delay: true
tcp-concurrent: true
# interface-name: enp6s18
log-level: warning
find-process-mode: 'off'
global-client-fingerprint: chrome
keep-alive-idle: 600
keep-alive-interval: 15
profile:
  store-selected: true
  store-fake-ip: true

# 为防止使用插件朋友遇到面板问题，我注释掉了此模块。
# 跑裸核朋友自行删除注释即可，使用nikki仅内核的ui路径改为/etc/nikki/run/ui
#external-controller: 0.0.0.0:9090
#secret: ""
#external-ui: "/etc/mihomo/ui"
#external-ui-name: zashboard
#external-ui-url: "https://github.com/Zephyruso/zashboard/archive/refs/heads/gh-pages.zip"

# 嗅探
sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain:
    - "+.v2ex.com"
  skip-domain:
    - "+.baidu.com"

# 入站  
tun:
  enable: true
  # system/gvisor/mixed
  stack: mixed
  dns-hijack: ["any:53", "tcp://any:53"]
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true



# DNS模块
dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: false
  respect-rules: true
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter-mode: blacklist
  proxy-server-nameserver:
    - https://223.5.5.5/dns-query
  direct-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  nameserver:
    - https://1.1.1.1/dns-query
  nameserver-policy:
    "rule-set:private_domain,cn_domain,apple_domain":
      - 223.5.5.5
      - 119.29.29.29
  fake-ip-filter:
    - "rule-set:private_domain,cn_domain,apple_domain"

# 出站策略，根据自己情况调整每个策略里分组排序，增删都可以，比如把美国自动放到第一个，比如删除香港故转，注意别漏掉表情逗号等。
# 如果相应分组没有筛选到对应的国家，请根据自己节点名字调整筛选关键字。
# 没有再使用锚点，是考虑很多新手修改难度，这样新手修改某个分组更容易些。
proxy-groups:
  - {name: 🚀 默认代理, type: select, proxies: [🇭🇰 香港手动, 🇯🇵 日本手动, 🇸🇬 狮城手动, 🇺🇲 美国手动, 🏁 落地节点, 🐸 手动选择, ♻️ 自动选择]}
  - {name: 📹 YouTube, type: select, proxies: [🇭🇰 香港手动, 🇯🇵 日本手动, 🇸🇬 狮城手动, 🇺🇲 美国手动, 🏁 落地节点, 🐸 手动选择]}
  - {name: 🍀 Google, type: select, proxies: [🇭🇰 香港手动, 🇯🇵 日本手动, 🇸🇬 狮城手动, 🇺🇲 美国手动, 🏁 落地节点, 🐸 手动选择]}
  - {name: 🧠 AI, type: select, proxies: [🇯🇵 日本手动, 🇸🇬 狮城手动, 🇺🇲 美国手动, 🏁 落地节点]}
  - {name: 👨‍💻 Github, type: select, proxies: [🇯🇵 日本手动, 🇭🇰 香港手动, 🇸🇬 狮城手动, 🇺🇲 美国手动, 🏁 落地节点, 🐸 手动选择]}
  - {name: 🐬 OneDrive, type: select, proxies: [🇯🇵 日本手动, 🇸🇬 狮城手动, 🇺🇲 美国手动, 🏁 落地节点, 🐸 手动选择]}
  - {name: 🪟 Microsoft, type: select, proxies: [🇯🇵 日本手动, 🇸🇬 狮城手动, 🇺🇲 美国手动, 🏁 落地节点, 🐸 手动选择]}
  - {name: 🎵 TikTok, type: select, proxies: [🇯🇵 日本手动, 🇸🇬 狮城手动, 🇺🇲 美国手动, 🏁 落地节点, 🐸 手动选择]}
  - {name: 📲 Telegram, type: select, proxies: [🇸🇬 狮城手动, 🇭🇰 香港手动, 🇯🇵 日本手动, 🇺🇲 美国手动, 🏁 落地节点, 🐸 手动选择]}
  - {name: 🎥 NETFLIX, type: select, proxies: [🇭🇰 香港手动, 🇯🇵 日本手动, 🇸🇬 狮城手动, 🇺🇲 美国手动, 🏁 落地节点, 🐸 手动选择]}
  - {name: 💶 PayPal, type: select, proxies: [🇭🇰 香港手动, 🇯🇵 日本手动, 🇸🇬 狮城手动, 🇺🇲 美国手动, 🏁 落地节点, 🐸 手动选择]}
  - {name: 🐟 漏网之鱼, type: select, proxies: [🚀 默认代理, 直连]}
  - {name: 🇭🇰 香港手动, type: select, include-all: true, filter: "(?i)🇭🇰|HK|hk|香港|港|HongKong"}
  - {name: 🇯🇵 日本手动, type: select, include-all: true, filter: "(?i)🇯🇵|JP|jp|日本|日|Japan"}
  - {name: 🇸🇬 狮城手动, type: select, include-all: true, filter: "(?i)新加坡|坡|狮城|SG|Singapore"}
  - {name: 🇺🇲 美国手动, type: select, include-all: true, filter: "(?i)🇺🇸|US|us|USA|美国|美|United States|America"}
  - {name: 🚀 中转节点, type: select, include-all: true, filter: "^((?!(网站|流量|地址|剩余|过期|免费|时间|有效|Traffic|ExpireDate|GB|Expire Date|落地)).)*$"}
  - {name: 🏁 落地节点, type: select, include-all: true, filter: "(?i)落地|终点|endpoint"}
  - {name: 🐸 手动选择, type: select, include-all: true, filter: "^((?!(网站|流量|地址|剩余|过期|免费|时间|有效|Traffic|ExpireDate|GB|Expire Date)).)*$"}
  - {name: 📶 SpeedTest, type: select, include-all: true, filter: "^((?!(网站|流量|地址|剩余|过期|免费|时间|有效|Traffic|ExpireDate|GB|Expire Date)).)*$"}
  - {name: ♻️ 自动选择, type: url-test, include-all: true, tolerance: 50, interval: 600, filter: "^((?!(官网|到期时间|剩余|流量|套餐|免费|订阅|直连|GB|Expire Date|Traffic|ExpireDate|落地)).)*$", url: "http://www.gstatic.com/generate_204"}
  - {name: 🌐 全部节点, type: select, include-all: true}

# 规则匹配
# 此规则部分没有做防泄露处理，因为弊严重大于利！
rules:
  - RULE-SET,private_ip,直连
  - RULE-SET,pt,直连
  - RULE-SET,private_domain,直连
  - DOMAIN-SUFFIX,qichiyu.com,🚀 默认代理
  - RULE-SET,proxylite,🚀 默认代理
  - RULE-SET,speed_test,📶 SpeedTest
  - RULE-SET,ai,🧠 AI
  - RULE-SET,github_domain,👨‍💻 Github
  - RULE-SET,youtube_domain,📹 YouTube
  - RULE-SET,google_domain,🍀 Google
  - RULE-SET,onedrive_domain,🐬 OneDrive
  - RULE-SET,microsoft_domain,🪟 Microsoft
  - RULE-SET,apple_domain,直连
  - RULE-SET,tiktok_domain,🎵 TikTok
  - RULE-SET,telegram_domain,📲 Telegram
  - RULE-SET,netflix_domain,🎥 NETFLIX
  - RULE-SET,paypal_domain,💶 PayPal
  - RULE-SET,apple_ip,直连,no-resolve
  - RULE-SET,google_ip,🍀 Google,no-resolve
  - RULE-SET,netflix_ip,🎥 NETFLIX,no-resolve
  - RULE-SET,telegram_ip,📲 Telegram,no-resolve
  - RULE-SET,geolocation-!cn,🚀 默认代理
  - RULE-SET,cn_domain,直连
  - RULE-SET,cn_ip,直连
  - MATCH,🐟 漏网之鱼

# 规则集
## type：可选http/file/inline  behavior：可选domain/ipcidr/classical format：可选yaml/text/mrs
rule-anchor:
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: mrs}
  domain: &domain {type: http, interval: 86400, behavior: domain, format: mrs}
  class: &class {type: http, interval: 86400, behavior: classical, format: text}
rule-providers:
  private_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs"}
  proxylite: { <<: *class, url: "https://raw.githubusercontent.com/qichiyuhub/rule/refs/heads/main/proxy.list"}
  ai: {  <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-ai-!cn.mrs" }
  youtube_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.mrs"}
  google_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.mrs"}
  github_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.mrs"}
  telegram_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.mrs"}
  netflix_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.mrs"}
  paypal_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/paypal.mrs"}
  onedrive_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/onedrive.mrs"}
  microsoft_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft.mrs"}
  apple_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple-cn.mrs"}
  speedtest_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/ookla-speedtest.mrs"}
  tiktok_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/tiktok.mrs"}
  geolocation-!cn: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.mrs"}
  cn_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs"}
  speed_test: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/speedtest.mrs"}
  pt: { <<: *class, url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Ruleset/PrivateTracker.list"}

  private_ip: {<<: *ip, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/private.mrs"}
  cn_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs"}
  google_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.mrs"}
  telegram_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.mrs"}
  netflix_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/netflix.mrs"}
  apple_ip: {<<: *ip, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo-lite/geoip/apple.mrs"}
